camera0: rtsp://metacam:8554/camera2
camera1: rtsp://metacam:8554/camera1
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1.5
# with tablet
# checkerboard_box_size_scale : 2.8
checkerboard_box_size_scale : 1.6
# with table 
# checkerboard_rows: 4
# checkerboard_columns: 6
checkerboard_rows: 7
checkerboard_columns: 10

cooldown: 200
